name: Build
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Toolchains
        run: sudo apt install clang lld llvm python3 git ninja-build libsdl2-dev nasm gcc-multilib &&
             git clone https://github.com/cute-engineering/cutekit && sudo pip install -e cutekit/

      - name: Install Packages
        run: cutekit i

      - name: Build Kernel (x86_64)
        run: cutekit b --target=kernel-x86_64

      - name: Build EFI (x86_64)
        run: cutekit b --target=efi-x86_64

      - name: Build Host
        run: cutekit b
